package com.schoolbus.entity;
// Generated 2016-4-21 22:32:06 by Hibernate Tools 4.3.1.Final

/**
 * Bus generated by hbm2java
 */
public class Bus implements java.io.Serializable {

	private Integer id;
	private String name;
	private Integer userId;
	private Integer lineId;
	private Integer lineOrientation;
	private Integer state;
	private String longitude;
	private String latitude;
	private String userName;
	private String lineName;
	private Integer curStationId;
	private Integer nextStationId;

	public Bus() {
	}

	public Bus(String name) {
		this.name = name;
	}

	public Bus(String name, Integer userId, Integer lineId, Integer lineOrientation, Integer state, String longitude,
			String latitude, String userName, String lineName, Integer curStationId, Integer nextStationId) {
		this.name = name;
		this.userId = userId;
		this.lineId = lineId;
		this.lineOrientation = lineOrientation;
		this.state = state;
		this.longitude = longitude;
		this.latitude = latitude;
		this.userName = userName;
		this.lineName = lineName;
		this.curStationId = curStationId;
		this.nextStationId = nextStationId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Integer getLineId() {
		return this.lineId;
	}

	public void setLineId(Integer lineId) {
		this.lineId = lineId;
	}

	public Integer getLineOrientation() {
		return this.lineOrientation;
	}

	public void setLineOrientation(Integer lineOrientation) {
		this.lineOrientation = lineOrientation;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getLineName() {
		return this.lineName;
	}

	public void setLineName(String lineName) {
		this.lineName = lineName;
	}

	public Integer getCurStationId() {
		return this.curStationId;
	}

	public void setCurStationId(Integer curStationId) {
		this.curStationId = curStationId;
	}

	public Integer getNextStationId() {
		return this.nextStationId;
	}

	public void setNextStationId(Integer nextStationId) {
		this.nextStationId = nextStationId;
	}

}
