package com.schoolbus.entity;
// Generated 2016-4-21 22:32:06 by Hibernate Tools 4.3.1.Final

/**
 * LineInfo generated by hbm2java
 */
public class LineInfo implements java.io.Serializable {

	private Integer id;
	private Integer lineId;
	private Integer orientation;
	private String longitude;
	private String latitude;
	private Integer priority;

	public LineInfo() {
	}

	public LineInfo(Integer lineId, Integer orientation, String longitude, String latitude, Integer priority) {
		this.lineId = lineId;
		this.orientation = orientation;
		this.longitude = longitude;
		this.latitude = latitude;
		this.priority = priority;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getLineId() {
		return this.lineId;
	}

	public void setLineId(Integer lineId) {
		this.lineId = lineId;
	}

	public Integer getOrientation() {
		return this.orientation;
	}

	public void setOrientation(Integer orientation) {
		this.orientation = orientation;
	}

	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

}
