package com.schoolbus.entity;
// Generated 2016-4-21 22:32:06 by Hibernate Tools 4.3.1.Final

/**
 * Station generated by hbm2java
 */
public class Station implements java.io.Serializable {

	private Integer id;
	private String name;
	private String longitude;
	private String latitude;
	private Integer state;

	public Station() {
	}

	public Station(String name, String longitude, String latitude) {
		this.name = name;
		this.longitude = longitude;
		this.latitude = latitude;
	}

	public Station(String name, String longitude, String latitude, Integer state) {
		this.name = name;
		this.longitude = longitude;
		this.latitude = latitude;
		this.state = state;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

}
