package com.schoolbus.entity;
// Generated 2016-4-21 22:32:06 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer id;
	private String account;
	private String username;
	private String password;
	private String email;
	private String phone;
	private Date createTime;
	private Integer userType;
	private Integer busId;
	private String busName;
	private Integer state;
	private Integer appointmentLine;
	private Integer appointmentOrientation;
	private Integer appointmentStationId;

	public User() {
	}

	public User(String account, String username, String password) {
		this.account = account;
		this.username = username;
		this.password = password;
	}

	public User(String account, String username, String password, String email, String phone, Date createTime,
			Integer userType, Integer busId, String busName, Integer state, Integer appointmentLine,
			Integer appointmentOrientation, Integer appointmentStationId) {
		this.account = account;
		this.username = username;
		this.password = password;
		this.email = email;
		this.phone = phone;
		this.createTime = createTime;
		this.userType = userType;
		this.busId = busId;
		this.busName = busName;
		this.state = state;
		this.appointmentLine = appointmentLine;
		this.appointmentOrientation = appointmentOrientation;
		this.appointmentStationId = appointmentStationId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Integer getUserType() {
		return this.userType;
	}

	public void setUserType(Integer userType) {
		this.userType = userType;
	}

	public Integer getBusId() {
		return this.busId;
	}

	public void setBusId(Integer busId) {
		this.busId = busId;
	}

	public String getBusName() {
		return this.busName;
	}

	public void setBusName(String busName) {
		this.busName = busName;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public Integer getAppointmentLine() {
		return this.appointmentLine;
	}

	public void setAppointmentLine(Integer appointmentLine) {
		this.appointmentLine = appointmentLine;
	}

	public Integer getAppointmentOrientation() {
		return this.appointmentOrientation;
	}

	public void setAppointmentOrientation(Integer appointmentOrientation) {
		this.appointmentOrientation = appointmentOrientation;
	}

	public Integer getAppointmentStationId() {
		return this.appointmentStationId;
	}

	public void setAppointmentStationId(Integer appointmentStationId) {
		this.appointmentStationId = appointmentStationId;
	}

}
